"""empty message

Revision ID: 371918f88e53
Revises: 
Create Date: 2023-10-11 16:54:04.948892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '371918f88e53'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('created_datetime', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('updated_datetime', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('ongoing', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo')
    # ### end Alembic commands ###
