"""empty message

Revision ID: 9c7106b60d84
Revises: 6025ba54ed7d
Create Date: 2023-10-11 17:37:39.299787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '9c7106b60d84'
down_revision: Union[str, None] = '6025ba54ed7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todo', 'item',
               existing_type=sa.VARCHAR(length=255, collation='Korean_Wansung_CI_AI'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todo', 'item',
               existing_type=sa.VARCHAR(length=50, collation='Korean_Wansung_CI_AI'),
               nullable=True)
    # ### end Alembic commands ###
