"""empty message

Revision ID: c7dd13622a99
Revises: 371918f88e53
Create Date: 2023-10-11 17:18:19.489567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'c7dd13622a99'
down_revision: Union[str, None] = '371918f88e53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todo', 'item',
               existing_type=sa.VARCHAR(length=50, collation='Korean_Wansung_CI_AI'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todo', 'item',
               existing_type=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    # ### end Alembic commands ###
